import React, { useEffect, useState } from 'react';
import { useAuth } from '../contexts/AuthContext';
import './CompletionCertificate.css';

interface WipeDetails {
  targetPath: string;
  algorithm: string;
  startTime: Date;
  endTime: Date;
  duration: number;
  passes: number;
  size?: string;
  status: 'success' | 'completed';
}

interface CompletionCertificateProps {
  wipeDetails: WipeDetails;
  onClose: () => void;
  onPrint?: () => void;
}

export default function CompletionCertificate({
  wipeDetails,
  onClose,
  onPrint,
}: CompletionCertificateProps): React.ReactElement {
  const { userEmail } = useAuth();
  const [certificateId] = useState(
    () =>
      `SWIPE-${Date.now().toString(36).toUpperCase()}-${Math.random().toString(36).substr(2, 4).toUpperCase()}`,
  );

  const formatDuration = (milliseconds: number): string => {
    const seconds = Math.floor(milliseconds / 1000);
    const minutes = Math.floor(seconds / 60);
    const hours = Math.floor(minutes / 60);

    if (hours > 0) {
      return `${hours}h ${minutes % 60}m ${seconds % 60}s`;
    } else if (minutes > 0) {
      return `${minutes}m ${seconds % 60}s`;
    } else {
      return `${seconds}s`;
    }
  };

  const formatDateTime = (date: Date): string => {
    return date.toLocaleString('en-US', {
      year: 'numeric',
      month: 'long',
      day: 'numeric',
      hour: '2-digit',
      minute: '2-digit',
      second: '2-digit',
      timeZoneName: 'short',
    });
  };

  const getAlgorithmDescription = (algorithm: string): string => {
    const descriptions: { [key: string]: string } = {
      dod5220: 'DoD 5220.22-M (3-pass)',
      gutmann: 'Gutmann Method (35-pass)',
      random: 'Random Overwrite',
      zeros: 'Zero Fill',
      ones: 'One Fill',
    };
    return descriptions[algorithm] || algorithm.toUpperCase();
  };

  const handlePrint = () => {
    if (onPrint) {
      onPrint();
    } else {
      window.print();
    }
  };

  const handleDownload = () => {
    // Create a downloadable text version of the certificate
    const certificateText = `
SECURE WIPE COMPLETION CERTIFICATE
==================================

Certificate ID: ${certificateId}
Generated: ${formatDateTime(new Date())}

WIPE OPERATION DETAILS
---------------------
Target: ${wipeDetails.targetPath}
Algorithm: ${getAlgorithmDescription(wipeDetails.algorithm)}
Passes: ${wipeDetails.passes}
${wipeDetails.size ? `Size: ${wipeDetails.size}` : ''}

TIMELINE
--------
Started: ${formatDateTime(wipeDetails.startTime)}
Completed: ${formatDateTime(wipeDetails.endTime)}
Duration: ${formatDuration(wipeDetails.duration)}

VERIFICATION
-----------
Status: ${wipeDetails.status.toUpperCase()}
Operator: ${userEmail || 'Unknown User'}

This certificate confirms that the specified data has been securely 
wiped using industry-standard algorithms and procedures.

Generated by Secure Wipe Professional
    `.trim();

    const blob = new Blob([certificateText], { type: 'text/plain' });
    const url = window.URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `SecureWipe-Certificate-${certificateId}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    window.URL.revokeObjectURL(url);
  };
  return (
    <div className="certificate-overlay" role="dialog" aria-modal="true">
      <div className="certificate-card" id="certificate-print-area">
        <header className="certificate-top">
          <div className="brand">
            <div className="logo-shield" aria-hidden>
              <span className="shield-icon">🛡️</span>
            </div>
            <div className="titles">
              <h1 className="certificate-title">SECURE WIPE</h1>
              <p className="certificate-subtitle">Completion Certificate</p>
            </div>
          </div>
          <div className="certificate-meta">
            <div className="certificate-id">ID: {certificateId}</div>
            <div className="certificate-generated">
              {formatDateTime(new Date())}
            </div>
          </div>
        </header>

        <main className="certificate-body">
          <section className="statement">
            <p>
              This certifies that the following secure data destruction
              operation was performed in accordance with recognized industry
              standards and documented procedures.
            </p>
          </section>

          <section className="details-grid">
            <div className="details-column">
              <h3 className="details-heading">Operation Details</h3>
              <dl>
                <dt>Target</dt>
                <dd>{wipeDetails.targetPath}</dd>

                <dt>Algorithm</dt>
                <dd>{getAlgorithmDescription(wipeDetails.algorithm)}</dd>

                <dt>Passes</dt>
                <dd>{wipeDetails.passes}</dd>

                {wipeDetails.size && (
                  <>
                    <dt>Size</dt>
                    <dd>{wipeDetails.size}</dd>
                  </>
                )}
              </dl>
            </div>

            <div className="details-column">
              <h3 className="details-heading">Timeline & Verification</h3>
              <dl>
                <dt>Started</dt>
                <dd>{formatDateTime(wipeDetails.startTime)}</dd>

                <dt>Completed</dt>
                <dd>{formatDateTime(wipeDetails.endTime)}</dd>

                <dt>Duration</dt>
                <dd>{formatDuration(wipeDetails.duration)}</dd>

                <dt>Status</dt>
                <dd className={`status-${wipeDetails.status}`}>
                  {wipeDetails.status.toUpperCase()}
                </dd>

                <dt>Operator</dt>
                <dd>{userEmail || 'System'}</dd>
              </dl>
            </div>
          </section>

          <section className="security-note">
            <div className="badge">
              <span className="security-icon">🔒</span>
              <div>
                <strong>Certified Secure</strong>
                <p>Data has been permanently destroyed and is unrecoverable.</p>
              </div>
            </div>
          </section>
        </main>

        <footer className="certificate-footer">
          <div className="footer-text">
            Generated by Secure Wipe Professional — Industrial Grade Data
            Sanitization
          </div>
          <div className="certificate-actions">
            <button className="btn primary" onClick={handlePrint}>
              🖨️ Print
            </button>
            <button className="btn secondary" onClick={handleDownload}>
              📥 Download (.txt)
            </button>
            <button className="btn" onClick={onClose}>
              ✖️ Close
            </button>
          </div>
        </footer>
      </div>
    </div>
  );
}
