import React, { useEffect, useState } from 'react';
import { useAuth } from '../contexts/AuthContext';

interface WipeDetails {
  targetPath: string;
  algorithm: string;
  startTime: Date;
  endTime: Date;
  duration: number;
  passes: number;
  size?: string;
  status: 'success' | 'completed';
}

interface CompletionCertificateProps {
  wipeDetails: WipeDetails;
  onClose: () => void;
  onPrint?: () => void;
}

export default function CompletionCertificate({
  wipeDetails,
  onClose,
  onPrint,
}: CompletionCertificateProps): React.ReactElement {
  const { userEmail } = useAuth();
  const [certificateId] = useState(
    () =>
      `SWIPE-${Date.now().toString(36).toUpperCase()}-${Math.random().toString(36).substr(2, 4).toUpperCase()}`,
  );

  const formatDuration = (milliseconds: number): string => {
    const seconds = Math.floor(milliseconds / 1000);
    const minutes = Math.floor(seconds / 60);
    const hours = Math.floor(minutes / 60);

    if (hours > 0) {
      return `${hours}h ${minutes % 60}m ${seconds % 60}s`;
    } else if (minutes > 0) {
      return `${minutes}m ${seconds % 60}s`;
    } else {
      return `${seconds}s`;
    }
  };

  const formatDateTime = (date: Date): string => {
    return date.toLocaleString('en-US', {
      year: 'numeric',
      month: 'long',
      day: 'numeric',
      hour: '2-digit',
      minute: '2-digit',
      second: '2-digit',
      timeZoneName: 'short',
    });
  };

  const getAlgorithmDescription = (algorithm: string): string => {
    const descriptions: { [key: string]: string } = {
      dod5220: 'DoD 5220.22-M (3-pass)',
      gutmann: 'Gutmann Method (35-pass)',
      random: 'Random Overwrite',
      zeros: 'Zero Fill',
      ones: 'One Fill',
    };
    return descriptions[algorithm] || algorithm.toUpperCase();
  };

  const handlePrint = () => {
    if (onPrint) {
      onPrint();
    } else {
      window.print();
    }
  };

  const handleDownload = () => {
    // Create a downloadable text version of the certificate
    const certificateText = `
SECURE WIPE COMPLETION CERTIFICATE
==================================

Certificate ID: ${certificateId}
Generated: ${formatDateTime(new Date())}

WIPE OPERATION DETAILS
---------------------
Target: ${wipeDetails.targetPath}
Algorithm: ${getAlgorithmDescription(wipeDetails.algorithm)}
Passes: ${wipeDetails.passes}
${wipeDetails.size ? `Size: ${wipeDetails.size}` : ''}

TIMELINE
--------
Started: ${formatDateTime(wipeDetails.startTime)}
Completed: ${formatDateTime(wipeDetails.endTime)}
Duration: ${formatDuration(wipeDetails.duration)}

VERIFICATION
-----------
Status: ${wipeDetails.status.toUpperCase()}
Operator: ${userEmail || 'Unknown User'}

This certificate confirms that the specified data has been securely 
wiped using industry-standard algorithms and procedures.

Generated by Secure Wipe Professional
    `.trim();

    const blob = new Blob([certificateText], { type: 'text/plain' });
    const url = window.URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `SecureWipe-Certificate-${certificateId}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    window.URL.revokeObjectURL(url);
  };

  return (
    <div className="certificate-overlay">
      <div className="certificate-container">
        <div className="certificate-content" id="certificate-print-area">
          {/* Certificate Header */}
          <div className="certificate-header">
            <div className="certificate-logo">
              <div className="logo-shield">
                <span className="shield-icon">🛡️</span>
              </div>
            </div>
            <h1 className="certificate-title">SECURE WIPE</h1>
            <h2 className="certificate-subtitle">COMPLETION CERTIFICATE</h2>
            <div className="certificate-id">
              Certificate ID: {certificateId}
            </div>
          </div>

          {/* Main Content */}
          <div className="certificate-main">
            <div className="certificate-statement">
              <p className="statement-text">
                This certificate confirms that a secure data wiping operation
                has been successfully completed in accordance with industry
                standards and best practices.
              </p>
            </div>

            {/* Operation Details */}
            <div className="certificate-details">
              <div className="details-section">
                <h3 className="section-title">OPERATION DETAILS</h3>
                <div className="details-grid">
                  <div className="detail-item">
                    <span className="detail-label">Target:</span>
                    <span className="detail-value">
                      {wipeDetails.targetPath}
                    </span>
                  </div>
                  <div className="detail-item">
                    <span className="detail-label">Algorithm:</span>
                    <span className="detail-value">
                      {getAlgorithmDescription(wipeDetails.algorithm)}
                    </span>
                  </div>
                  <div className="detail-item">
                    <span className="detail-label">Passes:</span>
                    <span className="detail-value">{wipeDetails.passes}</span>
                  </div>
                  {wipeDetails.size && (
                    <div className="detail-item">
                      <span className="detail-label">Size:</span>
                      <span className="detail-value">{wipeDetails.size}</span>
                    </div>
                  )}
                </div>
              </div>

              <div className="details-section">
                <h3 className="section-title">TIMELINE</h3>
                <div className="details-grid">
                  <div className="detail-item">
                    <span className="detail-label">Started:</span>
                    <span className="detail-value">
                      {formatDateTime(wipeDetails.startTime)}
                    </span>
                  </div>
                  <div className="detail-item">
                    <span className="detail-label">Completed:</span>
                    <span className="detail-value">
                      {formatDateTime(wipeDetails.endTime)}
                    </span>
                  </div>
                  <div className="detail-item">
                    <span className="detail-label">Duration:</span>
                    <span className="detail-value">
                      {formatDuration(wipeDetails.duration)}
                    </span>
                  </div>
                </div>
              </div>

              <div className="details-section">
                <h3 className="section-title">VERIFICATION</h3>
                <div className="details-grid">
                  <div className="detail-item">
                    <span className="detail-label">Status:</span>
                    <span className="detail-value status-success">
                      ✅ {wipeDetails.status.toUpperCase()}
                    </span>
                  </div>
                  <div className="detail-item">
                    <span className="detail-label">Operator:</span>
                    <span className="detail-value">
                      {userEmail || 'System'}
                    </span>
                  </div>
                  <div className="detail-item">
                    <span className="detail-label">Generated:</span>
                    <span className="detail-value">
                      {formatDateTime(new Date())}
                    </span>
                  </div>
                </div>
              </div>
            </div>

            {/* Security Statement */}
            <div className="certificate-security">
              <div className="security-badge">
                <span className="security-icon">🔒</span>
                <div className="security-text">
                  <strong>CERTIFIED SECURE</strong>
                  <p>
                    Data has been permanently destroyed and is unrecoverable
                  </p>
                </div>
              </div>
            </div>

            {/* Footer */}
            <div className="certificate-footer">
              <div className="footer-line"></div>
              <p className="footer-text">
                Generated by Secure Wipe Professional - Industrial Grade Data
                Sanitization
              </p>
              <p className="footer-subtext">
                This certificate serves as legal proof of data destruction
                compliance
              </p>
            </div>
          </div>
        </div>

        {/* Action Buttons */}
        <div className="certificate-actions">
          <button className="action-btn primary" onClick={handlePrint}>
            🖨️ Print Certificate
          </button>
          <button className="action-btn secondary" onClick={handleDownload}>
            📥 Download (.txt)
          </button>
          <button className="action-btn" onClick={onClose}>
            ✖️ Close
          </button>
        </div>
      </div>
    </div>
  );
}
